services:
  mysql:
    image: mysql:8
    ports:
      - 3306:3306
    volumes:
      - ./db:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_PASSWORD=password
      - MYSQL_USER=mysqlusr
      - MYSQL_DATABASE=typedids
    networks:
      - mysql_network

networks:
  mysql_network:
    driver: bridge
